
global:
  scrape_interval:     10s # El intervalo en el que se traerá las métricas

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: redis-exporter
    static_configs:
      - targets: ['redis-exporter:9121']
